name: localenv

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - pytorch=2.*
  - torchvision=0.*
  - pytorch-lightning=2.*
  - torchmetrics=0.*
  - torchaudio=0.*
  - hydra-core=1.*
  - pandas=1.5.*
  - librosa=0.*
  - tensorboard=2.*
  - scikit-image=0.*
  - torchmetrics=0.*
  - wandb=0.*