# this config file defines all the callbacks configuration used during training
# to add a new callback, create its configuration in the current directory and add it to defaults
defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - lr_monitor.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val_loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1