version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    runtime: nvidia

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
