version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./storage:/storage
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    runtime: nvidia
    volumes:
      - ./storage:/storage
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
