version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage